services:
  - type: web
    name: sandwich-platform-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sandwich-platform-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /health
    
  - type: pserv
    name: sandwich-platform-db
    env: postgresql
    region: oregon
    plan: starter
    databaseName: sandwich_platform
    databaseUser: sandwich_user
